# Generated by Django 3.1.5 on 2021-03-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210314_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='toDoList',
            new_name='todolist',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='date',
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
